name: webshot_api
description: A simple web API to generate images from a url, made using shelf package.
version: 1.0.0
homepage: https://www.github.com/EverythingSuckz/webshot-api

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  puppeteer: ^3.0.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  http: ^0.13.0
  lints: ^1.0.0
  test_process: ^2.0.0
  test: ^1.15.0
